#!/usr/bin/env bash

# cmdloop script is auto-started on boot by systemd symlink: 
# /etc/systemd/system/multi-user.target.wants/omxtv.service -> /opt/omxtv/omxtv.service

cd $(dirname $(readlink -f "$0")) 
. forall.sh                       #var logdir, pidfilecmdloop

maincmdfifo=$logdir/maincmdfifo

echo $$ > $pidfilecmdloop

while true; do
   [ -p $maincmdfifo ] || { mkfifo $maincmdfifo; chmod 666 $maincmdfifo; }
   read cmd < $maincmdfifo
   echo "switching command $cmd"
   ./controller $cmd
done
