#!/usr/bin/env bash

cd $(dirname $(readlink -f "$0")) ; . forall.sh #var logdir

cmd="$1"; [ -z $cmd ] && exit ; shift
csfile="$logdir/controllerstate"
state=$(filevar "$csfile" idle)
inarray $state idle playing || state=idle

function setstate() { state="$1"; echo $state > $csfile; }

osdpid=$(./tvosd start --x 0 --y 0 --pointsize 48 "$cmd")

case $state in
   idle)
      case $cmd in
         POWERON)    ./tools/daynight day  ; ./tv --lastusedchannel;         state=playing ;;
      esac
   ;;
   playing)
      case $cmd in
         POWEROFF)   ./tools/daynight night; ./tvloop stop; ./audio ontvoff; state=idle    ;;
         VOLUMEUP)   ./tvaudio up      ;;
         VOLUMEDOWN) ./tvaudio down    ;;
         MUTE)       ./tvaudio mute    ;;
         UNMUTE)     ./tvaudio unmute  ;;
         LOWRES)     ./tv --lastusedchannel --lowres ;;
         HIRES)      ./tv --lastusedchannel          ;;
         PLAYCH)     ./tv "$@"         ;;
      esac
   ;;
esac

setstate $state
kill $osdpid
