#!/usr/bin/env bash

username=$(head -n1 /etc/omxtv/userpass)
userpass=$(tail -n1 /etc/omxtv/userpass)
 authurl="https://www.bhtelecom.ba/index.php?id=6905&u=$username&p=$userpass&x=1"

while true; do
   wget -qO- "$authurl"
   sleep 600 # 10 minutes
done
