#!/usr/bin/env bash

if which cec-client; then
   case "$1" in
      day)   echo "on 0"      | cec-client -s ;;
      night) echo "standby 0" | cec-client -s ;;
   esac
else
   case "$1" in
      day)   /opt/vc/bin/tvservice -p ;;
      night) /opt/vc/bin/tvservice -o ;;
   esac
fi
